name: test

on:
  workflow_dispatch:

jobs:
  update_altstore_source:
    runs-on: ubuntu-latest

    steps:
    - name: Update Altstore Source with latest release
      run: |
        curl --location --request POST 'https://api.github.com/repos/Balackburn/YTLitePlusAltstore/dispatches' \
        --header 'Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "event_type": "update-altstore-source-trigger"
        }'